from typing import Any


class _Node:
    descriptor: str
    def rename(self, new_name: str | None) -> None:
        """Rename this node in the project (persisted). Pass None or '' to clear the rename."""
        ...
    def xrefs_to(self) -> list[Class | Method | Field]:
        """Nodes that reference this one (callers, field accesses, type uses)."""
        ...


class Class(_Node):
    """A class, identified by its smali descriptor e.g. 'Lcom/foo/Bar;'."""
    name: str
    package: str
    def methods(self) -> list[Method]:
        """Methods declared by this class."""
        ...
    def fields(self) -> list[Field]:
        """Fields declared by this class."""
        ...
    def java(self) -> str:
        """Decompiled Java source for this class (top-level parent for inner classes)."""
        ...
    def smali(self) -> str:
        """Disassembled smali/bytecode listing for this class."""
        ...
    def super_class(self) -> Class | None:
        """The superclass as a Class, or None."""
        ...
    def interfaces(self) -> list[Class]:
        """Implemented interfaces as Class objects."""
        ...
    def offset_at_line(self, line: int) -> int | None:
        """Bytecode offset (code units) for a 1-based decompiled-Java line, or None."""
        ...
    def strings(self) -> list[str]:
        """Distinct string literals referenced by this class's methods, in first-seen order."""
        ...
    def info(self) -> dict[str, Any] | None:
        """Structured metadata dict: descriptor, name, package, super, interfaces, access_flags, modifiers."""
        ...


class Method(_Node):
    """A method, identified as 'Lcom/foo/Bar;->name(args)ret'."""
    declaring_class: Class
    signature: str
    name: str
    def smali(self) -> str | None:
        """Disassembled smali/bytecode listing for just this method."""
        ...
    def instructions(self) -> list[dict[str, Any]] | None:
        """Structured bytecode rows, each a dict: offset, addr, line, mnemonic, operands, comment, resource."""
        ...
    def info(self) -> dict[str, Any] | None:
        """Structured metadata dict: descriptor, name, signature, return_type, arg_types, access_flags, modifiers, registers."""
        ...


class Field(_Node):
    """A field, identified as 'Lcom/foo/Bar;->name'."""
    declaring_class: Class
    name: str
    def info(self) -> dict[str, Any] | None:
        """Structured metadata dict: descriptor, name, type, access_flags, modifiers."""
        ...
    def reads(self) -> list[Method]:
        """Methods that read this field (IGET/SGET)."""
        ...
    def writes(self) -> list[Method]:
        """Methods that write this field (IPUT/SPUT)."""
        ...


class Dex:
    """A dex file jadx could not load, identified by the SHA-256 of its original bytes."""
    sha: str
    name: str
    problems: list[str]
    malformed: bool
    def bytes(self) -> bytes:
        """Current (patched) dex bytes."""
        ...
    def source_bytes(self) -> bytes:
        """Original unpatched dex bytes."""
        ...
    def validate(self, data: bytes | None = ...) -> list[str]:
        """Validation problems for the current bytes, or for `data` if given."""
        ...
    def repair(self) -> bool:
        """Auto-fix the dex header, save the fix as a patch, reload. Returns True if now valid."""
        ...
    def save(self, data: bytes) -> None:
        """Save hand-fixed `data` as the dex patch and reload (for fixes beyond the header)."""
        ...


class _Ui:
    """Interaction with the jdex window: dialogs and navigation."""
    def message(self, text: str) -> None:
        """Show an information dialog."""
        ...
    def error(self, text: str) -> None:
        """Show an error dialog."""
        ...
    def ask(self, prompt: str, default: str = "") -> str | None:
        """Prompt for a line of text; returns the entered string, or None if cancelled."""
        ...
    def confirm(self, text: str) -> bool:
        """Yes/No dialog; returns True if the user chose Yes."""
        ...
    def goto_offset(self, offset: int) -> None:
        """Reveal a file offset (int) in the bytecode view."""
        ...
    def open(self, node: _Node | str) -> None:
        """Reveal a Class, Method or Field (or a raw descriptor string) in the bytecode view."""
        ...


class _Debug:
    """Debugger control: attach, set breakpoints, step, inspect frames/locals."""
    @property
    def running(self) -> bool:
        """True when a debug session is attached, False when detached."""
        ...
    def devices(self) -> list[dict]:
        """Connected devices/emulators as {serial, label, online} dicts."""
        ...
    def processes(self, serial: str) -> list[dict]:
        """Running app processes on a device as {pid, name} dicts."""
        ...
    def attach(self, serial: str, pid: int) -> bool:
        """Attach the debugger to process `pid` on device `serial`. True on success."""
        ...
    def detach(self) -> None:
        """Detach the debugger and let the process run freely."""
        ...
    def resume(self) -> None:
        """Resume execution after a stop."""
        ...
    def pause(self) -> None:
        """Suspend the process at its current point."""
        ...
    def step_into(self) -> None:
        """Step into the next call."""
        ...
    def step_over(self) -> None:
        """Step over the next line."""
        ...
    def step_out(self) -> None:
        """Step out of the current method."""
        ...
    def breakpoint(self, descriptor, dex_pc: int = 0) -> None:
        """Set a breakpoint at a method descriptor (or Method) and dex offset (code units)."""
        ...
    def clear_breakpoint(self, descriptor, dex_pc: int = 0) -> None:
        """Remove a previously set breakpoint."""
        ...
    def state(self) -> str:
        """Current debugger state: 'detached', 'running' or 'stopped'."""
        ...
    def frames(self) -> list[dict]:
        """Call stack at the current stop as {index, description, descriptor, dex_pc} dicts."""
        ...
    def variables(self, frame_index: int = 0) -> list[dict]:
        """Local variables of a stack frame as {name, type, value} dicts."""
        ...
    def wait_until_stopped(self, timeout: float = 10.0, poll: float = 0.05) -> bool:
        """Block until the debugger is 'stopped' or `timeout` seconds elapse. True if stopped."""
        ...
    def read_memory(self, address: int, length: int) -> bytes | None:
        """Read `length` bytes of target memory at `address`; None if unavailable."""
        ...
    def write_memory(self, address: int, data: bytes) -> bool:
        """Write raw bytes to target memory at `address`. True on success."""
        ...
    def runtime_addr(self, native_id: str, vaddr: int) -> int | None:
        """Resolve a library vaddr ('libfoo.so', 0x1234) to its live runtime address; None if not loaded."""
        ...
    def patch_native(self, native_id: str, vaddr: int, asm: str) -> bool:
        """Assemble `asm` for the target arch and write it over the instruction at native_id+vaddr (live). True on success."""
        ...


class _EmuObject:
    """A jdex object built by emulation (jdex.emu.new). Read/write fields, call methods, or pass it
    anywhere a value is expected (hook set_arg, run/resolve args). Lives in the session world."""
    @property
    def type(self) -> str:
        """The object's type descriptor, e.g. 'Lcom/app/Foo;'."""
        ...
    def get(self, name: str): ...
    def set(self, name: str, value) -> "_EmuObject": ...
    def call(self, short_id: str, *args): ...
    def fields(self) -> dict: ...


class _HookCall:
    """A call intercepted by an emulator hook. set_arg/replace accept emulated-object handles."""
    @property
    def method(self) -> str: ...
    @property
    def receiver(self): ...
    @property
    def args(self) -> list: ...
    def set_arg(self, index: int, value) -> None: ...
    def replace(self, value) -> None: ...


class _Emulator:
    """Emulator: run/step/inspect dex methods in-process, replace values, register per-APK stubs, read resolved values."""
    @property
    def running(self) -> bool:
        """True when an emulation is active (a run is loaded/paused), False when detached."""
        ...
    def new(self, class_desc: str, ctor_sig: str = ..., *args) -> "_EmuObject | None":
        """Construct an object by emulating its <init> in the session world. Returns an object handle
        (.get/.set/.call/.fields) usable wherever a value is expected, or None if class/ctor unknown."""
        ...
    def run(self, descriptor, args: list = ..., pause_at_entry: bool = True) -> bool:
        """Start emulating a method with `args` (a list); stops at entry. True if started."""
        ...
    def detach(self) -> None:
        """Abort the current emulation."""
        ...
    def resume(self) -> None:
        """Resume after a stop."""
        ...
    def pause(self) -> None:
        """Request a stop at the next instruction."""
        ...
    def step_into(self) -> None:
        """Step into the next call."""
        ...
    def step_over(self) -> None:
        """Step over the next call."""
        ...
    def step_out(self) -> None:
        """Run until the current method returns."""
        ...
    def breakpoint(self, descriptor, dex_pc: int = 0) -> None:
        """Stop at a method and dex offset (code units)."""
        ...
    def clear_breakpoint(self, descriptor, dex_pc: int = 0) -> None:
        """Remove a breakpoint."""
        ...
    def run_to_cursor(self, descriptor, dex_pc: int) -> None:
        """Resume and stop once at a method+offset."""
        ...
    def state(self) -> str:
        """Current state: 'detached', 'running' or 'stopped'."""
        ...
    def frames(self) -> list[dict]:
        """Call stack as {index, description, descriptor, dex_pc} dicts."""
        ...
    def variables(self, frame_index: int = 0) -> list[dict]:
        """Registers of a frame as {name, type, value, ref, edit_key, available} dicts."""
        ...
    def children(self, ref: int) -> list[dict]:
        """Fields/elements of an object or array variable by its `ref`."""
        ...
    def set_value(self, edit_key: str, text: str) -> bool:
        """Set a register from its `edit_key` to parsed `text`. True on success."""
        ...
    def set_register(self, frame_index: int, reg: int, value) -> bool:
        """Replace register `reg` of a frame with `value`. True on success."""
        ...
    def return_value(self):
        """Return value of a finished emulation (None if unknown/void)."""
        ...
    def resolve(self, descriptor, args: list = ...) -> dict:
        """Abstractly analyse a method; returns {return, unknown}."""
        ...
    def register_field(self, cls: str, name: str, value) -> None:
        """Register a constant value for a framework static field."""
        ...
    def register_stub(self, cls: str, name: str, fn) -> None:
        """Implement an unimplemented framework method: fn(receiver, args) -> value."""
        ...
    def await_stop(self, timeout: float = 5.0) -> bool:
        """Block until stopped/finished or `timeout` seconds elapse. True if stopped."""
        ...
    def await_finished(self, timeout: float = 5.0) -> bool:
        """Block until the emulation finishes or `timeout` seconds elapse. True if finished."""
        ...
    def hook(self, descriptor, callback) -> int:
        """Intercept calls to `descriptor` (full signature); returns an id for unhook(). callback(call) may call.set_arg(i, v) and/or call.replace(v)."""
        ...
    def unhook(self, hook_id: int) -> bool: ...
    def hooks(self) -> list[dict]:
        """List installed hooks as [{id, descriptor}] (they persist across runs)."""
        ...
    def clear_hooks(self) -> None: ...


class _Context:
    """The session running right now in the UI; None when nothing is running."""
    @property
    def emu(self) -> _Emulator: ...
    @property
    def debug(self) -> _Debug: ...


class _NativeEmulator:
    """Native (unidbg, ARM-only) emulator/debugger over an APK `.so`."""
    def decrypt(self, lib: str, cls: str, method_sig: str, cipher) -> str | None:
        """Run a native decryptor and return the plaintext (cipher: bytes/list jbyteArray or str jstring)."""
        ...
    def run(self, lib: str, cls: str, method_sig: str, args: list = ...) -> bool:
        """Emulate a JNI-bound native method, pausing at entry (args: bytes/str/ints)."""
        ...
    def load(self, lib: str) -> bool: ...
    def malloc(self, size: int) -> int: ...
    def mem_read(self, address: int, size: int) -> bytes: ...
    def mem_write(self, address: int, data) -> bool: ...
    def reg_read(self, name: str) -> int | None: ...
    def reg_write(self, name: str, value: int) -> bool: ...
    def call(self, address: int, *args) -> int | None: ...
    def emulate(self, begin: int, until: int) -> int | None: ...
    def detach(self) -> None: ...
    def resume(self) -> None: ...
    def step_into(self) -> None: ...
    def step_over(self) -> None: ...
    def step_out(self) -> None: ...
    def symbol(self, name: str) -> int | None:
        """Runtime address of an exported symbol."""
        ...
    def module_base(self) -> int: ...
    def breakpoint(self, address: int) -> None: ...
    def clear_breakpoint(self, address: int) -> None: ...
    def state(self) -> str: ...
    def frames(self) -> list[dict]: ...
    def registers(self) -> dict:
        """Guest registers at the current stop: {name: value}."""
        ...
    def set_register(self, name: str, value: int) -> bool: ...
    def write_memory(self, address: int, data) -> bool: ...
    def patch(self, file_offset: int, asm: str) -> bool:
        """Assemble and patch an instruction at a .so file offset (Keystone)."""
        ...
    def return_value(self): ...
    def await_stop(self, timeout: float = 5.0) -> bool: ...
    def await_finished(self, timeout: float = 5.0) -> bool: ...
    def on_syscall(self, callback) -> bool:
        """Intercept syscalls before unidbg handles them; callback(ctx) returns True if handled (set
        the result via ctx.set_ret), else False/None. ctx: number(), arg(i), reg(name), read_mem,
        write_mem, set_ret(v) (and set_arg/set_reg/ret)."""
        ...
    def clear_syscall(self) -> None: ...
    def hook(self, address: int, on_enter=None, on_leave=None) -> int:
        """Inline-hook the function at a runtime address; on_enter(ctx)/on_leave(ctx). Returns an unhook id."""
        ...
    def replace(self, address: int, callback) -> int:
        """Replace a function; callback(ctx) -> int forces the return (original skipped), None runs it."""
        ...
    def unhook(self, hook_id: int) -> bool: ...
    def mem_watch(self, begin: int, end: int, on_read=None, on_write=None) -> int:
        """A read/write watchpoint over the guest memory range [begin, end].

        on_read(acc) and on_write(acc) receive a memory-access view exposing address(), size(),
        value() (the written value; 0 for reads), is_write(), reg(name), set_reg(name, value),
        read_mem(addr, size) and write_mem(addr, data). Returns the watchpoint id, removable with
        unhook().
        """
        ...
    def trace(self, callback, begin: int = 0, end: int = 0) -> int:
        """A basic-block trace over [begin, end], or over the whole image when begin == end == 0.

        callback(block) receives a view exposing address(), size() and the same register and memory
        accessors as a watchpoint. Returns the trace id, removable with unhook().
        """
        ...
    def modules(self) -> list[dict]:
        """The loaded native modules, each as {name, base, size}: the target library and its
        dependencies (libc, libdl, ...)."""
        ...
    def symbol_at(self, address: int) -> dict | None:
        """The nearest exported symbol at or below a runtime address, as {name, module, offset}, or
        None when no module maps the address. offset is measured from the symbol's start."""
        ...


class _Config:
    """Deobfuscation engine configuration. Setters re-analyze the project so changes take effect."""
    emulator_enabled: bool
    decrypt_strings_at_startup: bool
    code_cleanup: bool
    passes: list[str]
    @property
    def available_passes(self) -> list[str]:
        """All toggleable deobfuscation pass ids."""
        ...
    def apply(self, emulator_enabled: bool | None = None, decrypt_strings_at_startup: bool | None = None, code_cleanup: bool | None = None, passes: list[str] | None = None) -> None:
        """Set any subset of options at once and re-analyze the project once."""
        ...


class _Jdex:
    """Top-level scripting facade, bound as `jdex`."""
    ui: _Ui
    debug: _Debug
    emu: _Emulator
    native_emu: _NativeEmulator
    this: _Context
    config: _Config
    def files(self) -> list[str]:
        """Names of every file entry inside the loaded APK (or the dex name for a bare dex)."""
        ...
    def read_file(self, path: str) -> bytes:
        """Raw bytes of one APK entry by name; empty bytes if absent."""
        ...
    def assemble(self, asm: str, arch: str, address: int = 0) -> bytes | None:
        """Assemble instruction text to bytes for `arch` ('arm64','arm','x86','x86_64','mips','mips64'); None on error."""
        ...
    def import_file(self, name: str, data: bytes) -> None:
        """Add a file (bytes) under `name`, type auto-detected: dex -> analysis,
        native ELF -> detected lib/<abi>/, else -> 'unknown'. Prompts to override
        if the name already exists in the project."""
        ...
    def classes(self) -> list[Class]:
        """All classes including inner classes."""
        ...
    def get_class(self, name: str) -> Class | None:
        """Look up a class by descriptor ('Lcom/foo/Bar;') or dotted name ('com.foo.Bar'); None if absent."""
        ...
    def find_classes(self, pattern: str) -> list[Class]:
        """Classes whose descriptor or simple name matches the regex `pattern`."""
        ...
    def find_methods(self, pattern: str) -> list[Method]:
        """Methods across all classes whose descriptor matches the regex `pattern`."""
        ...
    def find_fields(self, pattern: str) -> list[Field]:
        """Fields across all classes whose descriptor matches the regex `pattern`."""
        ...
    def strings(self) -> list[dict[str, Any]]:
        """Every string literal across all classes as dicts {value, method}. Expensive: scans all bytecode."""
        ...
    def search_code(self, pattern: str, limit: int = 1000) -> list[dict[str, Any]]:
        """Bytecode lines matching regex `pattern`, as dicts {method, offset, text}. Expensive full scan, capped at `limit`."""
        ...
    def set_annotation(self, node, offset: int, text: str | None) -> None:
        """Attach or replace a annotation."""
        ...
    def clear_annotations(self) -> None:
        """Remove all annotations."""
        ...
    def manifest(self) -> str:
        """Decoded AndroidManifest.xml text, '' if none."""
        ...
    def permissions(self) -> list[str]:
        """Requested permission names from <uses-permission>."""
        ...
    def components(self, kind: str = "activity") -> list[str]:
        """Declared component names for a manifest tag: activity, service, receiver or provider."""
        ...
    def app_package(self) -> str | None:
        """Application package id, or None."""
        ...
    def main_activity(self) -> str | None:
        """Launcher activity class name, or None."""
        ...
    def malformed_dexes(self) -> list[Dex]:
        """Dex files jadx could not load, as Dex objects you can inspect and repair."""
        ...
    def jadx(self) -> Any:
        """The raw jadx JadxDecompiler, for anything the facade does not cover."""
        ...


jdex: _Jdex
